### PR TITLE
Fixed current module name not being set when Model is instantiated

### PR DESCRIPTION
**Pull request by keilanknight**
As discussed on youtube! Cheers.

### CODE REVIEW

**Comment by jakecastelli** [comment]
Hi Keilan (Tref), is this the same error when you do `$this->model->get();`?

> Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order by id' at line 1 in /Applications/XAMPP/xamppfiles/htdocs/dbtest/engine/Model.php:133 Stack trace: #0

**Comment by keilanknight** [comment]
Hi Jake, yes that was exactly it. If I enable debugging it shows   SELECT *
FROM order by id  as the query.  The get_table_from_url method now returns
the current module name and this is called if no table name is passed to
any of the query methods, hence it looked like it was never actually being
set. I am on PHP 7.4  , I know there is something in PHP 8 about auto
promotion of properties in the constructors, but don't know if that's what
could have been the case here? (Not used it). Cheers!

**Comment by jakecastelli** [comment]
That was the clearest explanation I ever heard! Great job 👍

**Review by jakecastelli — APPROVED** [review]

**Comment by davidjconnelly** [comment]
Yes.  It's good to see the contributors list growing.

**Pull request merged**
