### PR TITLE
faster & better  custom routes

### PR DESCRIPTION
**Pull request by timlalev**
Make custom routing more robust and bit faster.
Handles rare cases where people may put capital letters in the url.

### CODE REVIEW

**Comment by timlalev** [comment]
Make custom routing more robust and bit faster.
Handles rare cases where people may put capital letters in the url.

**Comment by davidjconnelly** [comment]
Thanks.  I haven't tested it but I'm sure it's cool.  Many thanks for that!

**Comment by davidjconnelly** [comment]
Hi Tim.  I had a look and that is awesome.  Just one thing... would it be okay to get rid of the strtolower?

**Comment by timlalev** [comment]
Sure, the only reason it's there is to still work when people type capital letters in URL but it will absolutely work fine in any other case.

**Pull request merged**
